services:
  mysql:
    image: 'mysql:8.0-oracle'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE_NAME}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'
