spring:
  application:
    name: thoughts
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  datasource:
    url: "${MYSQL_URI}/${MYSQL_DATABASE_NAME}"
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

logging:
  level:
#    root: debug
    me.rahul.thoughts: DEBUG   # Specific logging level for the 'dev.some.flare' package
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
app:
  security:
    secret-key: ${SECRET_KEY}
  sendgrid:
    api-key: ${SENDGRID_MAIL_API_KEY}
    from-email: imrahulkumar590@gmail.com
    from-name: Rahul
